name: Generate Infra Secrets File

on:
  workflow_dispatch:
  push:

jobs:
  generate-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate access/secret keys and store in file
        run: |
          # Generate random keys
          prod_access=$(openssl rand -hex 12)
          prod_secret=$(openssl rand -hex 24)
          dev_access=$(openssl rand -hex 12)
          dev_secret=$(openssl rand -hex 24)
          prod_api="https://prod.example.com/api"
          dev_api="https://dev.example.com/api"

          # Use printf to avoid YAML errors and implicit key issues
          printf "%s\n" \
            "infra_node_object:" \
            "  prod_db:" \
            "    api: '${prod_api}'" \
            "    access_key: '${prod_access}'" \
            "    secret_key: '${prod_secret}'" \
            "  dev_db:" \
            "    api:'${dev_api}'" \
            "    access_key: '${dev_access}'" \
            "    secret_key: '${dev_secret}'" > infra_secrets.yml

      - name: Show generated secrets file (debug only)
        run: cat infra_secrets.yml
