name: Capture Ansible Output to Access Key

on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest  # This uses the GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code, including any playbooks

    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook to Capture Access Key
      id: ansible_debug
      run: |
        # Run the playbook and capture the output of infra_object_storage
        result=$(ansible-playbook test_playbook.yml | grep -oP 'infra_object_storage: \K.*')
        echo "access_key=$result" >> $GITHUB_ENV  # Set the access_key as an environment variable

    - name: Display Access Key
      run: |
        echo "Access Key: ${{ env.access_key }}"
