name: Test Ansible Command

on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Debug Command to Capture Access Key
      id: ansible_debug
      run: |
        # Run the Ansible command and capture the output
        result=$(ansible localhost, -m debug -a "var='infra_object_storage'" | grep -oP 'infra_object_storage: \K.*')
        echo "Captured result: $result"  # Display the result

    - name: Display Captured Result
      run: |
        echo "Captured Result: $result"
