name: Capture Ansible Output to Access Key

on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest  # This uses the GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code, including any playbooks

    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook to Capture Access Key
      id: ansible_debug
      run: |
        # Run the playbook explicitly targeting localhost with -c local
        result=$(ansible-playbook test_playbook.yml -i localhost, -c local | grep -oP 'infra_object_storage: \K.*')
        echo "ACCESS_KEY=$result" >> "$GITHUB_OUTPUT"  # Set the access_key as output

    - name: Display Access Key
      run: |
        echo "Access Key: ${{ steps.ansible_debug.outputs.ACCESS_KEY }}"