name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: |
          echo "Building the app..."
          mkdir -p output
          echo "Hello from the build artifact!" > output/app.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: output/
